#!/bin/sh
# Installs the tools this course's labs use, at the versions of the LearnSome.tech lab sandbox, on x86-64
# Ubuntu: the dev container (Dockerfile) and CI (.github/workflows/check.yml) both run it, as root.
# `install-tools.sh ci` leaves out the Linux userland the labs call, which CI does not need.
# Generated by the LearnSome.tech platform (scripts/labs-repos); do not edit here.
set -eu
if [ "$(uname -m)" != x86_64 ]; then
  echo "install-tools.sh: x86-64 Linux only (Codespaces, GitHub Actions); elsewhere install the tools yourself" >&2
  exit 1
fi
mode=${1:-full}
here=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
fetch() { curl -fsSL --retry 3 "$1" -o "$2" && echo "$3  $2" | sha256sum -c - >/dev/null; }

export DEBIAN_FRONTEND=noninteractive
apt-get update -q
apt-get install -y -q --no-install-recommends bash git unzip xz-utils ca-certificates curl
if [ "$mode" != ci ]; then
  apt-get install -y -q --no-install-recommends procps iproute2 util-linux findutils coreutils psmisc lsof strace less tree bc xxd binutils file acl gettext-base netcat-openbsd dnsutils iputils-ping traceroute net-tools openssh-client make patch bsdextrautils shellcheck
  # The sandbox's git is Ubuntu's; the base image puts a newer build first on PATH.
  if [ -x /usr/local/bin/git ] && [ -x /usr/bin/git ]; then ln -sf /usr/bin/git /usr/local/bin/git; fi
fi
rm -rf /var/lib/apt/lists/*
mkdir -p /opt/lab

# Python 3.14.7
fetch 'https://github.com/astral-sh/python-build-standalone/releases/download/20260924/cpython-3.14.7%2B20260924-x86_64-unknown-linux-gnu-install_only_stripped.tar.gz' "$tmp/python.tgz" bd0d0568ccded07bbf1c87727230dc5dd0187e706a87da23c4de78388a229b78
mkdir -p /opt/python && tar -xzf "$tmp/python.tgz" -C /opt/python --strip-components=1
ln -sf /opt/python/bin/python3.14 /usr/local/bin/python3
ln -sf /opt/python/bin/python3.14 /usr/local/bin/python

# Terraform 1.16.4, with the sandbox's offline mirror of the local, null and random providers
fetch 'https://releases.hashicorp.com/terraform/1.16.4/terraform_1.16.4_linux_amd64.zip' "$tmp/tf.zip" dc94af0eef1147718ad7c8daea792ed199e3e0492eec180d0adafa2a65a879df
mkdir -p /opt/terraform && unzip -q -o "$tmp/tf.zip" terraform -d /opt/terraform && chmod 0755 /opt/terraform/terraform
for p in "local 2.9.1 a8ea1c155bd5e0d695a28d3c0e2f542de8844e1791ea021f015a3f08e1c059e1" "null 3.3.2 d2855b922ea345dbd89ea287e4c6c4757e38bc0aaffeb2b79aa0b8004f9c53ff" "random 3.9.0 c51f15a031edfd6f23ce8ced3446ca7f8d8d647e2499890d7d5d10d5016d7257"; do
  # shellcheck disable=SC2086 # split the entry into its three fields
  set -- $p
  fetch "https://releases.hashicorp.com/terraform-provider-$1/$2/terraform-provider-$1_$2_linux_amd64.zip" "$tmp/provider.zip" "$3"
  dir="/opt/lab/terraform/providers/registry.terraform.io/hashicorp/$1/$2/linux_amd64"
  mkdir -p "$dir" && unzip -q -o "$tmp/provider.zip" -d "$dir"
done
install -m 0644 "$here/cli.tfrc" /opt/lab/terraform/cli.tfrc
install -m 0755 "$here/terraform" /usr/local/bin/terraform

# actionlint 1.7.12
fetch 'https://github.com/rhysd/actionlint/releases/download/v1.7.12/actionlint_1.7.12_linux_amd64.tar.gz' "$tmp/actionlint.tgz" 8aca8db96f1b94770f1b0d72b6dddcb1ebb8123cb3712530b08cc387b349a3d8
tar -xzf "$tmp/actionlint.tgz" -C /usr/local/bin actionlint && chmod 0755 /usr/local/bin/actionlint
